name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: create .env file
      run: echo "VITE_BACK_URL=${{ secrets.VITE_BACK_URL }}" > .env
      
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: leocutolo/frontend:latest
    
    - name: Run docker container
      run: docker run -d -p 8080:8080 --name frontend leocutolo/frontend:latest
    
    - name: sleep 1 min
      run: |
        sleep 1m
    
    - name: Test webpage
      run: |
        curl -sSf localhost:8080 >/dev/null
        if [ $? -ne 0 ]; then
          echo "Page not found."
          exit 1
        else
          echo "Page found."
        fi
    
    - name: Push to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leocutolo/frontend:latest
